### ISSUE TITLE
Redesign I/O system, I really don't know what this is...

### ISSUE THREAD

**Issue by SirMathhman** [Meticuli-Technologies/Nexus#59]

**Comment by SirMathhman** [comment]
Help me @agahEbrahimi

**Comment by ivanvinski** [comment]
Could you explain how does this I/O system work? I could help you, but I'm not sure how exactly is it supposed to work.

**Comment by SirMathhman** [comment]
Well, the IO system itself internally runs on Sockets and Streams. However that design at the moment is not necessarily scalable and or reliable. I've been thinking about different approaches to replace the system. When the system is replaced, then we can close this issue.

**Comment by SirMathhman** [comment]
The idea is to have a Client and Server class interact in the back end, and have two GUI applications in the front end.
